name = "App-MigrateToTest2V0"
# badges = ["travis-ci.com"]
module_maker="ModuleBuildTiny"
static_install = "auto"
readme_from = "script/migrate-to-test2-v0"
abstract_from = "script/migrate-to-test2-v0"
